function [params, species] = chromatinInitialize()
% This file is automatically generated by update_model.m from the chromatin_model spreadsheet
% Model URL: F:/enhancer_dynamics/model_v2/paramscan/chromatin_model.xlsx


% PARAMETERS
params(1,1) = 10; % Widom 2011
params(1,2) = 3; % Hill coefficient for TF binding
params(1,3) = 0.025; % Kd for TF binding
params(2,1) = 75; % Widom 2011
params(3,1) = 12; % Widom 2011
params(3,2) = 3; % Hill coefficient for TF binding
params(3,3) = 0.025; % Kd for TF binding
params(4,1) = 60; % Widom 2011
params(5,1) = 14.4; % Widom 2011
params(5,2) = 3; % Hill coefficient for TF binding
params(5,3) = 0.025; % Kd for TF binding
params(6,1) = 48; % Widom 2011
params(7,1) = 17.28; % Widom 2011
params(7,2) = 3; % Hill coefficient for TF binding
params(7,3) = 0.025; % Kd for TF binding
params(8,1) = 38.4; % Widom 2011
params(9,1) = 20.736; % Widom 2011
params(9,2) = 3; % Hill coefficient for TF binding
params(9,3) = 0.025; % Kd for TF binding
params(10,1) = 30.72; % Widom 2011
params(11,1) = 24.8832; % Widom 2011
params(11,2) = 3; % Hill coefficient for TF binding
params(11,3) = 0.025; % Kd for TF binding
params(12,1) = 24.576; % Widom 2011
params(13,1) = 29.8598; % Widom 2011
params(13,2) = 3; % Hill coefficient for TF binding
params(13,3) = 0.025; % Kd for TF binding
params(14,1) = 19.6608; % Widom 2011
params(15,1) = 35.8318; % Widom 2011
params(15,2) = 3; % Hill coefficient for TF binding
params(15,3) = 0.025; % Kd for TF binding
params(16,1) = 15.7286; % Widom 2011
params(17,1) = 42.9982; % Widom 2011
params(17,2) = 3; % Hill coefficient for TF binding
params(17,3) = 0.025; % Kd for TF binding
params(18,1) = 12.5829; % Widom 2011
params(19,1) = 51.5978; % Widom 2011
params(19,2) = 3; % Hill coefficient for TF binding
params(19,3) = 0.025; % Kd for TF binding
params(20,1) = 10.0663; % Widom 2011
params(21,1) = 61.9174; % Widom 2011
params(21,2) = 3; % Hill coefficient for TF binding
params(21,3) = 0.025; % Kd for TF binding
params(22,1) = 8.05306; % Widom 2011
params(23,1) = 74.3008; % Widom 2011
params(23,2) = 3; % Hill coefficient for TF binding
params(23,3) = 0.025; % Kd for TF binding
params(24,1) = 6.44245; % Widom 2011
params(25,1) = 89.161; % Widom 2011
params(25,2) = 3; % Hill coefficient for TF binding
params(25,3) = 0.025; % Kd for TF binding
params(26,1) = 5.15396; % Widom 2011
params(27,1) = 106.993; % Widom 2011
params(27,2) = 3; % Hill coefficient for TF binding
params(27,3) = 0.025; % Kd for TF binding
params(28,1) = 4.12317; % Widom 2011


% SPECIES
species.NAMES = {...
'E_0' ...1
'E_1' ...2
'E_2' ...3
'E_3' ...4
'E_4' ...5
'E_5' ...6
'E_6' ...7
'E_7' ...8
'E_8' ...9
'E_9' ...10
'E_10' ...11
'E_11' ...12
'E_12' ...13
'E_13' ...14
'E_14' ...15
};